name: test-environment
channels:
  - conda-forge
dependencies:
  - xarray
  - dask
  - distributed
  - toolz
  - sphinx
  - pyyaml
  - coveralls
  - coverage
  - codecov
  - behave
  - mock
  - zarr
  - satpy
  - h5netcdf
  - pyorbital
  - pytest
  - pytest-cov
  - pygrib
  - appdirs
  - pip
  - pip:
    - trollsift
    - posttroll
